---
repos:
 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v2.3.0
   hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-toml

 - repo: https://github.com/nbQA-dev/nbQA
   rev: 1.5.3
   hooks:
    - id: nbqa-black
      additional_dependencies: [ black==22.12.0 ]
      types: [jupyter]
    - id: nbqa-pyupgrade
      args: ["--py37-plus"]
      types: [jupyter]
 - repo: https://github.com/kynan/nbstripout
   rev: 0.4.0
   hooks:
     - id: nbstripout
       name: nbstripout - Strip outputs from notebooks (auto-fixes)
       args:
         - --extra-keys
         - "metadata.colab metadata.kernelspec cell.metadata.colab cell.metadata.executionInfo cell.metadata.id cell.metadata.outputId"
